language: r
sudo: required

r:
  - oldrel
  - release
  - devel
cache: packages

# need this for current nlme:
r_packages:
  - nlme


after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    recipients:
      - huangracer@gmail.com
      - fabian.scheipl@stat.uni-muenchen.de
      - jeff.goldsmith@columbia.edu
      - jgellar1@jhu.edu
      - mathew.w.mclean@gmail.com
    on_success: change
    on_failure: always

