# see http://docs.travis-ci.com/user/languages/r/
language: r

# Be strict when checking our package
warnings_are_errors: true

# Use github version of testthat
- ./travis-tool.sh install_github hadley/testthat