# see http://docs.travis-ci.com/user/languages/r/
language: r
sudo: required
# Be strict when checking our package
warnings_are_errors: true

# Use github version of testthat
r_github_packages:
 - hadley/testthat
 - jimhester/covr

# remove default --as-cran so testthat tests are run (also avoids two useless check notes)
r_check_args: --no-manual --no-vignettes

notifications:
  email:
    recipients:
      - mathew.w.mclean@gmail.com
    on_success: change # always|never|change, default: change
    on_failure: always # default: always

after_success:
 - Rscript -e 'library(covr);capture.output(coveralls())'
